import type {
  GraphicsWorkspaceMode,
  SocialGraphicsElement,
  SocialGraphicsScene,
  SocialGraphicsTemplateId,
  SocialGraphicsTemplateOption,
} from '../types'

export const SOCIAL_GRAPHICS_WIDTH = 1920
export const SOCIAL_GRAPHICS_HEIGHT = 1080

const templateModeMap: Record<SocialGraphicsTemplateId, GraphicsWorkspaceMode> = {
  'informed-design-event': 'social',
  'educational-slide': 'social',
  'operational-snapshot': 'briefing',
  'decision-support-focus': 'briefing',
}

const templateOptions: SocialGraphicsTemplateOption[] = [
  {
    id: 'operational-snapshot',
    label: 'Operational Snapshot',
    description: 'Core partner slide for conditions, impacts, and confidence.',
  },
  {
    id: 'decision-support-focus',
    label: 'Decision Support Focus',
    description: 'Concise partner-facing slide for operational decisions and messaging.',
  },
  {
    id: 'educational-slide',
    label: 'Phenomena Slide',
    description: 'Phenomena-based explainer slide for education and outreach content.',
  },
]

const templateLabelMap = Object.fromEntries(
  templateOptions.map((option) => [option.id, option.label]),
) as Record<SocialGraphicsTemplateId, string>

function cloneScene(scene: SocialGraphicsScene): SocialGraphicsScene {
  return JSON.parse(JSON.stringify(scene)) as SocialGraphicsScene
}

function buildScene(
  templateId: SocialGraphicsTemplateId,
  title: string,
  elements: SocialGraphicsElement[],
): SocialGraphicsScene {
  return {
    version: 'social-graphics-v1',
    title,
    templateId,
    width: SOCIAL_GRAPHICS_WIDTH,
    height: SOCIAL_GRAPHICS_HEIGHT,
    elements,
  }
}

function background(fill: string): SocialGraphicsElement {
  return {
    id: 'background',
    name: 'Background',
    kind: 'rect',
    x: 0,
    y: 0,
    width: SOCIAL_GRAPHICS_WIDTH,
    height: SOCIAL_GRAPHICS_HEIGHT,
    visible: true,
    opacity: 1,
    fill,
    cornerRadius: 0,
  }
}

function buildBackgroundImage(): SocialGraphicsElement {
  return {
    id: 'background-image',
    name: 'Background Image',
    kind: 'image',
    x: 0,
    y: 0,
    width: SOCIAL_GRAPHICS_WIDTH,
    height: SOCIAL_GRAPHICS_HEIGHT,
    visible: false,
    opacity: 1,
    src: '',
    fit: 'cover',
    cornerRadius: 0,
    assetRole: 'background',
    linkedAssetId: null,
  }
}

function buildLogo(x = 1540, y = 72, width = 240, height = 240): SocialGraphicsElement {
  return {
    id: 'logo',
    name: 'Logo',
    kind: 'image',
    x,
    y,
    width,
    height,
    visible: true,
    opacity: 1,
    src: '/NOAA_logo.png',
    fit: 'contain',
    cornerRadius: 0,
    assetRole: 'logo',
    linkedAssetId: 'noaa-brand-mark',
  }
}

function buildLockedBrandImage({
  id,
  name,
  x,
  y,
  width,
  height,
  src,
}: {
  id: string
  name: string
  x: number
  y: number
  width: number
  height: number
  src: string
}): SocialGraphicsElement {
  return {
    id,
    name,
    kind: 'image',
    x,
    y,
    width,
    height,
    visible: true,
    opacity: 1,
    src,
    fit: 'contain',
    cornerRadius: 0,
    locked: true,
  }
}

function buildImageSlot({
  id,
  name,
  x,
  y,
  width,
  height,
  src,
  fit = 'contain',
  cornerRadius = 0,
  assetRole,
  linkedAssetId = null,
}: {
  id: string
  name: string
  x: number
  y: number
  width: number
  height: number
  src: string
  fit?: 'cover' | 'contain'
  cornerRadius?: number
  assetRole?: 'background' | 'logo' | 'main-image' | 'secondary-image' | 'icon-slot'
  linkedAssetId?: string | null
}): SocialGraphicsElement {
  return {
    id,
    name,
    kind: 'image',
    x,
    y,
    width,
    height,
    visible: true,
    opacity: 1,
    src,
    fit,
    cornerRadius,
    assetRole,
    linkedAssetId,
  }
}

function buildImagePlaceholder({
  id,
  name,
  x,
  y,
  width,
  height,
  text = 'Insert Chosen Asset',
}: {
  id: string
  name: string
  x: number
  y: number
  width: number
  height: number
  text?: string
}): SocialGraphicsElement {
  return {
    id,
    name,
    kind: 'text',
    x,
    y,
    width,
    height,
    visible: true,
    opacity: 1,
    text,
    fill: 'rgba(255, 255, 255, 0.78)',
    fontFamily: 'DejaVu Sans',
    fontSize: 34,
    fontWeight: 600,
    align: 'center',
    lineHeight: 1.2,
  }
}

const informedDesignEventScene = buildScene('informed-design-event', 'Informed Design Event', [
  background('#e9ecef'),
  buildBackgroundImage(),
  {
    id: 'outer-shell',
    name: 'Outer Shell',
    kind: 'rect',
    x: 84,
    y: 64,
    width: 1752,
    height: 952,
    visible: true,
    opacity: 1,
    fill: '#f7f8fa',
    cornerRadius: 0,
  },
  {
    id: 'header-band',
    name: 'Header Band',
    kind: 'rect',
    x: 84,
    y: 64,
    width: 1752,
    height: 20,
    visible: true,
    opacity: 1,
    fill: '#11a7de',
    cornerRadius: 0,
  },
  {
    id: 'left-rail',
    name: 'Left Rail',
    kind: 'rect',
    x: 84,
    y: 84,
    width: 268,
    height: 932,
    visible: true,
    opacity: 1,
    fill: '#355c9c',
    cornerRadius: 0,
  },
  {
    id: 'content-shell',
    name: 'Content Shell',
    kind: 'rect',
    x: 178,
    y: 126,
    width: 1508,
    height: 746,
    visible: true,
    opacity: 1,
    fill: '#1f1f22',
    cornerRadius: 0,
  },
  {
    id: 'title',
    name: 'Title',
    kind: 'text',
    x: 240,
    y: 158,
    width: 820,
    height: 108,
    visible: true,
    opacity: 1,
    text: 'Hazardous Space Weather Travel',
    fill: '#ffffff',
    fontFamily: 'DejaVu Sans',
    fontSize: 66,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.02,
  },
  {
    id: 'headline-deck',
    name: 'Headline Deck',
    kind: 'text',
    x: 244,
    y: 238,
    width: 720,
    height: 84,
    visible: true,
    opacity: 1,
    text: 'Strong geomagnetic conditions may create degraded communications and navigation concerns through tonight.',
    fill: '#f2f4f7',
    fontFamily: 'DejaVu Sans',
    fontSize: 30,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.16,
  },
  {
    id: 'timing-badge',
    name: 'Timing Badge',
    kind: 'rect',
    x: 1088,
    y: 152,
    width: 484,
    height: 74,
    visible: true,
    opacity: 1,
    fill: '#ffffff',
    cornerRadius: 0,
  },
  {
    id: 'timing-text',
    name: 'Timing Text',
    kind: 'text',
    x: 1140,
    y: 170,
    width: 386,
    height: 42,
    visible: true,
    opacity: 1,
    text: 'Through Early Wednesday UTC',
    fill: '#2d2f36',
    fontFamily: 'DejaVu Sans',
    fontSize: 34,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1,
  },
  {
    id: 'timing-accent',
    name: 'Timing Accent',
    kind: 'line',
    x: 1088,
    y: 226,
    width: 484,
    height: 0,
    visible: true,
    opacity: 1,
    stroke: '#f79f3b',
    strokeWidth: 10,
  },
  {
    id: 'photo-frame',
    name: 'Photo Frame',
    kind: 'rect',
    x: 242,
    y: 324,
    width: 748,
    height: 372,
    visible: true,
    opacity: 1,
    fill: '#203746',
    cornerRadius: 0,
  },
  buildImageSlot({
    id: 'main-image',
    name: 'Main Image',
    x: 242,
    y: 324,
    width: 748,
    height: 372,
    src: '',
    fit: 'cover',
    cornerRadius: 0,
    assetRole: 'main-image',
    linkedAssetId: null,
  }),
  buildImagePlaceholder({
    id: 'main-image-placeholder',
    name: 'Main Image Placeholder',
    x: 318,
    y: 466,
    width: 596,
    height: 88,
  }),
  {
    id: 'severity-panel',
    name: 'Severity Panel',
    kind: 'rect',
    x: 242,
    y: 700,
    width: 334,
    height: 132,
    visible: true,
    opacity: 1,
    fill: '#252629',
    cornerRadius: 0,
  },
  {
    id: 'severity-title',
    name: 'Severity Title',
    kind: 'text',
    x: 266,
    y: 726,
    width: 214,
    height: 32,
    visible: true,
    opacity: 1,
    text: 'Weather Risk',
    fill: '#ffffff',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'risk-scale-red',
    name: 'Risk Scale Red',
    kind: 'rect',
    x: 266,
    y: 770,
    width: 176,
    height: 26,
    visible: true,
    opacity: 1,
    fill: '#f44336',
    cornerRadius: 2,
  },
  {
    id: 'risk-scale-orange',
    name: 'Risk Scale Orange',
    kind: 'rect',
    x: 266,
    y: 800,
    width: 120,
    height: 26,
    visible: true,
    opacity: 1,
    fill: '#ff9f2f',
    cornerRadius: 2,
  },
  {
    id: 'risk-scale-yellow',
    name: 'Risk Scale Yellow',
    kind: 'rect',
    x: 266,
    y: 830,
    width: 88,
    height: 26,
    visible: true,
    opacity: 1,
    fill: '#e8df67',
    cornerRadius: 2,
  },
  {
    id: 'risk-label',
    name: 'Risk Label',
    kind: 'text',
    x: 466,
    y: 786,
    width: 90,
    height: 52,
    visible: true,
    opacity: 1,
    text: 'High',
    fill: '#ffffff',
    fontFamily: 'DejaVu Sans',
    fontSize: 32,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1,
  },
  {
    id: 'summary-head',
    name: 'Summary Head',
    kind: 'text',
    x: 1088,
    y: 272,
    width: 482,
    height: 88,
    visible: true,
    opacity: 1,
    text: 'Expected impacts will create hazardous operating conditions for HF communications, aviation routing, and GNSS-dependent planning.',
    fill: '#f79f3b',
    fontFamily: 'DejaVu Sans',
    fontSize: 32,
    fontWeight: 700,
    align: 'center',
    lineHeight: 1.2,
  },
  {
    id: 'impact-card',
    name: 'Impact Card',
    kind: 'rect',
    x: 1088,
    y: 374,
    width: 484,
    height: 220,
    visible: true,
    opacity: 1,
    fill: '#ffffff',
    cornerRadius: 0,
  },
  buildImageSlot({
    id: 'hazard-icon',
    name: 'Hazard Icon',
    x: 1098,
    y: 392,
    width: 108,
    height: 108,
    src: '',
    fit: 'contain',
    cornerRadius: 18,
    assetRole: 'icon-slot',
    linkedAssetId: null,
  }),
  buildImagePlaceholder({
    id: 'icon-slot-placeholder',
    name: 'Icon Slot Placeholder',
    x: 1106,
    y: 424,
    width: 92,
    height: 54,
    text: 'no files yet',
  }),
  {
    id: 'impact-copy',
    name: 'Impact Copy',
    kind: 'text',
    x: 1238,
    y: 392,
    width: 318,
    height: 170,
    visible: true,
    opacity: 1,
    text: 'HF users may experience intermittent degradation.\nNavigation confidence may narrow during peak activity windows.',
    fill: '#23262c',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.26,
  },
  {
    id: 'impact-divider',
    name: 'Impact Divider',
    kind: 'line',
    x: 1088,
    y: 596,
    width: 484,
    height: 0,
    visible: true,
    opacity: 1,
    stroke: '#f79f3b',
    strokeWidth: 3,
  },
  {
    id: 'actions-head',
    name: 'Actions Head',
    kind: 'text',
    x: 1088,
    y: 630,
    width: 250,
    height: 38,
    visible: true,
    opacity: 1,
    text: 'Actions to take...',
    fill: '#f79f3b',
    fontFamily: 'DejaVu Sans',
    fontSize: 34,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'actions-copy',
    name: 'Actions Copy',
    kind: 'text',
    x: 1088,
    y: 688,
    width: 486,
    height: 132,
    visible: true,
    opacity: 1,
    text: 'Delay non-critical communications windows.\nMessage timing confidence and affected sectors.\nUse simple, action-oriented wording for partners and the public.',
    fill: '#23262c',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.28,
  },
  {
    id: 'bottom-band',
    name: 'Bottom Band',
    kind: 'rect',
    x: 178,
    y: 872,
    width: 1508,
    height: 144,
    visible: true,
    opacity: 1,
    fill: '#242426',
    cornerRadius: 0,
  },
  {
    id: 'resource-copy',
    name: 'Resource Copy',
    kind: 'text',
    x: 540,
    y: 924,
    width: 680,
    height: 56,
    visible: true,
    opacity: 1,
    text: 'weather.gov/SWPC | Operational Decision Support | Updated 18Z',
    fill: '#f3f6fb',
    fontFamily: 'DejaVu Sans',
    fontSize: 26,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.2,
  },
  buildLogo(216, 896, 112, 112),
])

const operationalSnapshotScene = buildScene('operational-snapshot', 'Operational Snapshot', [
  background('#08121e'),
  buildBackgroundImage(),
  {
    id: 'header-band',
    name: 'Header Band',
    kind: 'rect',
    x: 0,
    y: 0,
    width: SOCIAL_GRAPHICS_WIDTH,
    height: 212,
    visible: true,
    opacity: 1,
    fill: '#0f2a47',
    cornerRadius: 0,
  },
  {
    id: 'title',
    name: 'Title',
    kind: 'text',
    x: 128,
    y: 72,
    width: 980,
    height: 96,
    visible: true,
    opacity: 1,
    text: 'Operational Snapshot',
    fill: '#f7fbff',
    fontFamily: 'DejaVu Sans',
    fontSize: 78,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.04,
  },
  {
    id: 'summary-card',
    name: 'Summary Card',
    kind: 'rect',
    x: 112,
    y: 274,
    width: 760,
    height: 640,
    visible: true,
    opacity: 1,
    fill: '#0b223b',
    cornerRadius: 28,
  },
  {
    id: 'summary-text',
    name: 'Summary Text',
    kind: 'text',
    x: 152,
    y: 324,
    width: 676,
    height: 526,
    visible: true,
    opacity: 1,
    text: 'Conditions:\nMinor geomagnetic response remains possible.\n\nImpacts:\nHF users may see intermittent degradation.\nGNSS effects remain limited but possible near higher latitudes.\n\nConfidence:\nModerate through the next 24 hours.',
    fill: '#deebf9',
    fontFamily: 'DejaVu Sans',
    fontSize: 34,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.4,
  },
  {
    id: 'image-frame',
    name: 'Image Frame',
    kind: 'rect',
    x: 938,
    y: 274,
    width: 848,
    height: 640,
    visible: true,
    opacity: 1,
    fill: '#102d4b',
    cornerRadius: 28,
  },
  {
    id: 'secondary-image',
    name: 'Secondary Image',
    kind: 'image',
    x: 984,
    y: 322,
    width: 754,
    height: 544,
    visible: true,
    opacity: 1,
    src: '',
    fit: 'contain',
    cornerRadius: 20,
    assetRole: 'main-image',
    linkedAssetId: null,
  },
  buildImagePlaceholder({
    id: 'main-image-placeholder',
    name: 'Main Image Placeholder',
    x: 1114,
    y: 548,
    width: 494,
    height: 72,
  }),
  buildLogo(1604, 32, 164, 164),
])

const decisionSupportFocusScene = buildScene('decision-support-focus', 'Decision Support Focus', [
  background('#06101a'),
  buildBackgroundImage(),
  {
    id: 'top-accent',
    name: 'Top Accent',
    kind: 'rect',
    x: 108,
    y: 96,
    width: 540,
    height: 18,
    visible: true,
    opacity: 1,
    fill: '#62c4ff',
    cornerRadius: 9,
  },
  {
    id: 'title',
    name: 'Title',
    kind: 'text',
    x: 108,
    y: 154,
    width: 980,
    height: 174,
    visible: true,
    opacity: 1,
    text: 'Decision Support Focus',
    fill: '#f7fbff',
    fontFamily: 'DejaVu Sans',
    fontSize: 88,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.02,
  },
  {
    id: 'subtitle',
    name: 'Subtitle',
    kind: 'text',
    x: 112,
    y: 360,
    width: 930,
    height: 330,
    visible: true,
    opacity: 1,
    text: 'Use this slide to frame the operational decision, the expected impact window, and the recommended communication posture for partners and leadership.',
    fill: '#dce9f8',
    fontFamily: 'DejaVu Sans',
    fontSize: 40,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.34,
  },
  {
    id: 'decision-card',
    name: 'Decision Card',
    kind: 'rect',
    x: 1156,
    y: 170,
    width: 620,
    height: 712,
    visible: true,
    opacity: 1,
    fill: '#0d2743',
    cornerRadius: 30,
  },
  {
    id: 'decision-header',
    name: 'Decision Header',
    kind: 'text',
    x: 1212,
    y: 232,
    width: 500,
    height: 68,
    visible: true,
    opacity: 1,
    text: 'Operational Focus',
    fill: '#f8fbff',
    fontFamily: 'DejaVu Sans',
    fontSize: 40,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'decision-body',
    name: 'Decision Body',
    kind: 'text',
    x: 1212,
    y: 330,
    width: 500,
    height: 450,
    visible: true,
    opacity: 1,
    text: 'Decision:\nElevate partner awareness messaging.\n\nWindow:\n00Z to 18Z tomorrow.\n\nWhy it matters:\nMinor communication disruptions remain possible during key planning periods.',
    fill: '#dbe8f6',
    fontFamily: 'DejaVu Sans',
    fontSize: 32,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.42,
  },
  buildLogo(1556, 898, 172, 172),
])

const educationalSlideScene = buildScene('educational-slide', 'Educational Slide', [
  background('#ffffff'),
  buildBackgroundImage(),
  {
    id: 'feature-block',
    name: 'Feature Block',
    kind: 'rect',
    x: 0,
    y: 0,
    width: 960,
    height: 1080,
    visible: true,
    opacity: 1,
    fill: '#102643',
    cornerRadius: 0,
    locked: true,
  },
  {
    id: 'feature-rule-left',
    name: 'Feature Rule Left',
    kind: 'line',
    x: 96,
    y: 96,
    width: 198,
    height: 0,
    visible: true,
    opacity: 1,
    stroke: '#ffffff',
    strokeWidth: 3,
    locked: true,
  },
  {
    id: 'feature-rule-right',
    name: 'Feature Rule Right',
    kind: 'line',
    x: 486,
    y: 96,
    width: 198,
    height: 0,
    visible: true,
    opacity: 1,
    stroke: '#ffffff',
    strokeWidth: 3,
    locked: true,
  },
  {
    id: 'feature-label',
    name: 'Feature Label',
    kind: 'text',
    x: 298,
    y: 82,
    width: 184,
    height: 42,
    visible: true,
    opacity: 1,
    text: 'SWPC',
    fill: '#fff9fb',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 700,
    align: 'center',
    lineHeight: 1,
    locked: true,
  },
  {
    id: 'feature-mission',
    name: 'Feature Mission',
    kind: 'text',
    x: 184,
    y: 126,
    width: 412,
    height: 42,
    visible: true,
    opacity: 1,
    text: 'Safeguarding Society with Actionable Space Weather Information',
    fill: 'rgba(233, 241, 252, 0.76)',
    fontFamily: 'DejaVu Sans',
    fontSize: 16,
    fontWeight: 400,
    align: 'center',
    lineHeight: 1.18,
    locked: true,
  },
  buildImageSlot({
    id: 'education-graphic',
    name: 'Education Graphic',
    x: 82,
    y: 252,
    width: 796,
    height: 386,
    src: '',
    fit: 'cover',
    cornerRadius: 0,
    assetRole: 'main-image',
    linkedAssetId: null,
  }),
  buildImagePlaceholder({
    id: 'main-image-placeholder',
    name: 'Main Image Placeholder',
    x: 140,
    y: 400,
    width: 680,
    height: 92,
  }),
  {
    id: 'education-title',
    name: 'Education Title',
    kind: 'text',
    x: 88,
    y: 864,
    width: 784,
    height: 108,
    visible: true,
    opacity: 1,
    text: 'What is a Coronal Mass Ejection?',
    fill: '#ffffff',
    fontFamily: 'DejaVu Sans',
    fontSize: 34,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.08,
    locked: true,
  },
  {
    id: 'right-panel',
    name: 'Right Panel',
    kind: 'rect',
    x: 960,
    y: 0,
    width: 960,
    height: 1080,
    visible: true,
    opacity: 1,
    fill: '#ffffff',
    cornerRadius: 0,
    locked: true,
  },
  {
    id: 'topic-kicker',
    name: 'Topic Kicker',
    kind: 'text',
    x: 1024,
    y: 92,
    width: 520,
    height: 40,
    visible: true,
    opacity: 1,
    text: 'Education & Outreach',
    fill: '#5a5f69',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1,
    locked: true,
  },
  {
    id: 'topic-title',
    name: 'Topic Title',
    kind: 'text',
    x: 1024,
    y: 136,
    width: 860,
    height: 124,
    visible: true,
    opacity: 1,
    text: 'Coronal Mass Ejection (CME)',
    fill: '#1f5f8b',
    fontFamily: 'DejaVu Sans',
    fontSize: 50,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.02,
    locked: true,
  },
  {
    id: 'topic-subtitle',
    name: 'Topic Subtitle',
    kind: 'text',
    x: 1024,
    y: 258,
    width: 760,
    height: 84,
    visible: false,
    opacity: 1,
    text: '',
    fill: '#5b6068',
    fontFamily: 'DejaVu Sans',
    fontSize: 30,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.28,
    locked: true,
  },
  {
    id: 'content-divider',
    name: 'Content Divider',
    kind: 'line',
    x: 1024,
    y: 286,
    width: 800,
    height: 0,
    visible: true,
    opacity: 1,
    stroke: '#d7dbe3',
    strokeWidth: 3,
    locked: true,
  },
  {
    id: 'meaning-title',
    name: 'Meaning Title',
    kind: 'text',
    x: 1024,
    y: 326,
    width: 250,
    height: 40,
    visible: true,
    opacity: 1,
    text: 'What it is:',
    fill: '#555962',
    fontFamily: 'DejaVu Sans',
    fontSize: 32,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'meaning-copy',
    name: 'Meaning Copy',
    kind: 'text',
    x: 1024,
    y: 382,
    width: 304,
    height: 210,
    visible: true,
    opacity: 1,
    text: 'A coronal mass ejection, or CME, is a large cloud of magnetized solar material released from the Sun into space.',
    fill: '#4b4f58',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.32,
  },
  {
    id: 'why-title',
    name: 'Why Title',
    kind: 'text',
    x: 1440,
    y: 326,
    width: 340,
    height: 40,
    visible: true,
    opacity: 1,
    text: 'Why it matters:',
    fill: '#555962',
    fontFamily: 'DejaVu Sans',
    fontSize: 32,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'why-copy',
    name: 'Why Copy',
    kind: 'text',
    x: 1440,
    y: 382,
    width: 340,
    height: 210,
    visible: true,
    opacity: 1,
    text: "When a CME reaches Earth, it can disturb Earth's magnetic field and trigger geomagnetic storm conditions.",
    fill: '#4b4f58',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.32,
  },
  {
    id: 'sectors-divider',
    name: 'Sectors Divider',
    kind: 'line',
    x: 1024,
    y: 646,
    width: 800,
    height: 0,
    visible: true,
    opacity: 1,
    stroke: '#d6d9de',
    strokeWidth: 2,
    locked: true,
  },
  {
    id: 'sectors-title',
    name: 'Sectors Title',
    kind: 'text',
    x: 1024,
    y: 686,
    width: 276,
    height: 38,
    visible: true,
    opacity: 1,
    text: 'Sectors at Risk:',
    fill: '#555962',
    fontFamily: 'DejaVu Sans',
    fontSize: 30,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'sector-icon-1',
    name: 'Sector Icon 1',
    kind: 'rect',
    x: 1318,
    y: 698,
    width: 14,
    height: 14,
    visible: true,
    opacity: 1,
    fill: '#1f5f8b',
    cornerRadius: 7,
    locked: true,
  },
  {
    id: 'sector-row-1',
    name: 'Sector Row 1',
    kind: 'text',
    x: 1344,
    y: 688,
    width: 432,
    height: 30,
    visible: true,
    opacity: 1,
    text: 'GNSS / positioning',
    fill: '#4b4f58',
    fontFamily: 'DejaVu Sans',
    fontSize: 24,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'sector-icon-2',
    name: 'Sector Icon 2',
    kind: 'rect',
    x: 1318,
    y: 734,
    width: 14,
    height: 14,
    visible: true,
    opacity: 1,
    fill: '#1f5f8b',
    cornerRadius: 7,
    locked: true,
  },
  {
    id: 'sector-row-2',
    name: 'Sector Row 2',
    kind: 'text',
    x: 1344,
    y: 724,
    width: 432,
    height: 30,
    visible: true,
    opacity: 1,
    text: 'Satellite',
    fill: '#4b4f58',
    fontFamily: 'DejaVu Sans',
    fontSize: 24,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'sector-icon-3',
    name: 'Sector Icon 3',
    kind: 'rect',
    x: 1318,
    y: 770,
    width: 14,
    height: 14,
    visible: true,
    opacity: 1,
    fill: '#1f5f8b',
    cornerRadius: 7,
    locked: true,
  },
  {
    id: 'sector-row-3',
    name: 'Sector Row 3',
    kind: 'text',
    x: 1344,
    y: 760,
    width: 432,
    height: 30,
    visible: true,
    opacity: 1,
    text: 'Power grid',
    fill: '#4b4f58',
    fontFamily: 'DejaVu Sans',
    fontSize: 24,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'sector-icon-4',
    name: 'Sector Icon 4',
    kind: 'rect',
    x: 1318,
    y: 806,
    width: 14,
    height: 14,
    visible: true,
    opacity: 1,
    fill: '#1f5f8b',
    cornerRadius: 7,
    locked: true,
  },
  {
    id: 'sector-row-4',
    name: 'Sector Row 4',
    kind: 'text',
    x: 1344,
    y: 796,
    width: 432,
    height: 30,
    visible: true,
    opacity: 1,
    text: 'Communications',
    fill: '#4b4f58',
    fontFamily: 'DejaVu Sans',
    fontSize: 24,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'footer-rule',
    name: 'Footer Rule',
    kind: 'line',
    x: 1024,
    y: 910,
    width: 800,
    height: 0,
    visible: false,
    opacity: 1,
    stroke: '#d6d9de',
    strokeWidth: 2,
    locked: true,
  },
  {
    id: 'resource-line-1',
    name: 'Resource Line 1',
    kind: 'text',
    x: 1148,
    y: 956,
    width: 410,
    height: 34,
    visible: true,
    opacity: 1,
    text: 'swpc.noaa.gov',
    fill: '#2c2f37',
    fontFamily: 'DejaVu Sans',
    fontSize: 32,
    fontWeight: 700,
    align: 'right',
    lineHeight: 1,
    locked: true,
  },
  {
    id: 'resource-line-2',
    name: 'Resource Line 2',
    kind: 'text',
    x: 1044,
    y: 990,
    width: 514,
    height: 26,
    visible: true,
    opacity: 1,
    text: 'Space Weather Prediction Center • Boulder, CO',
    fill: '#505762',
    fontFamily: 'DejaVu Sans',
    fontSize: 20,
    fontWeight: 400,
    align: 'right',
    lineHeight: 1,
    locked: true,
  },
  {
    id: 'resource-line-3',
    name: 'Resource Line 3',
    kind: 'text',
    x: 1148,
    y: 1018,
    width: 410,
    height: 24,
    visible: true,
    opacity: 1,
    text: 'Updated: --',
    fill: '#3b89c9',
    fontFamily: 'DejaVu Sans',
    fontSize: 18,
    fontWeight: 400,
    align: 'right',
    lineHeight: 1,
    locked: true,
  },
  buildLockedBrandImage({
    id: 'noaa-brand-lockup',
    name: 'NOAA Brand Lockup',
    x: 1682,
    y: 930,
    width: 112,
    height: 112,
    src: '/assets/visual-finder/logos/noaa-emblem-rgb-withspace-2022.png',
  }),
  buildLockedBrandImage({
    id: 'nws-brand-lockup',
    name: 'NWS Brand Lockup',
    x: 1792,
    y: 942,
    width: 92,
    height: 92,
    src: '/assets/visual-finder/logos/NWSlogo.png',
  }),
])

const scenes: Record<SocialGraphicsTemplateId, SocialGraphicsScene> = {
  'informed-design-event': informedDesignEventScene,
  'operational-snapshot': operationalSnapshotScene,
  'decision-support-focus': decisionSupportFocusScene,
  'educational-slide': educationalSlideScene,
}

export function createSceneFromTemplate(templateId: SocialGraphicsTemplateId): SocialGraphicsScene {
  return cloneScene(scenes[templateId])
}

export function getGraphicsTemplateOptions(mode: GraphicsWorkspaceMode): SocialGraphicsTemplateOption[] {
  return templateOptions.filter((option) => templateModeMap[option.id] === mode)
}

export function getDefaultTemplateId(mode: GraphicsWorkspaceMode): SocialGraphicsTemplateId {
  const match = templateOptions.find((option) => templateModeMap[option.id] === mode)
  return match?.id ?? (mode === 'social' ? 'educational-slide' : 'operational-snapshot')
}

export function templateBelongsToMode(
  templateId: SocialGraphicsTemplateId,
  mode: GraphicsWorkspaceMode,
): boolean {
  return templateModeMap[templateId] === mode
}

export function graphicsTemplateLabel(templateId: SocialGraphicsTemplateId): string {
  return templateLabelMap[templateId]
}
