import type {
  GraphicsWorkspaceMode,
  SocialGraphicsElement,
  SocialGraphicsScene,
  SocialGraphicsTemplateId,
  SocialGraphicsTemplateOption,
} from '../types'

export const SOCIAL_GRAPHICS_WIDTH = 1920
export const SOCIAL_GRAPHICS_HEIGHT = 1080

const templateModeMap: Record<SocialGraphicsTemplateId, GraphicsWorkspaceMode> = {
  'briefing-summary': 'social',
  'event-alert-card': 'social',
  'informed-design-event': 'social',
  'educational-slide': 'social',
  'partner-spotlight': 'social',
  'partner-impact-brief': 'briefing',
  'operational-snapshot': 'briefing',
  'decision-support-focus': 'briefing',
}

const templateOptions: SocialGraphicsTemplateOption[] = [
  {
    id: 'briefing-summary',
    label: 'Briefing Summary',
    description: "Full-width headline card for the day's operational summary.",
  },
  {
    id: 'event-alert-card',
    label: 'Event / Alert Card',
    description: 'High-contrast event card with a stronger alert treatment.',
  },
  {
    id: 'informed-design-event',
    label: 'Informed Design Event',
    description: 'Research-informed hazard card with clear timing, severity, impacts, and actions.',
  },
  {
    id: 'partner-spotlight',
    label: 'Partner Spotlight',
    description: 'Announcement-style card with a partner feature panel.',
  },
  {
    id: 'partner-impact-brief',
    label: 'Partner Impact Brief',
    description: 'Single-briefing slide focused on partner impacts and actions.',
  },
  {
    id: 'operational-snapshot',
    label: 'Operational Snapshot',
    description: 'Core partner slide for conditions, impacts, and confidence.',
  },
  {
    id: 'decision-support-focus',
    label: 'Decision Support Focus',
    description: 'Concise partner-facing slide for operational decisions and messaging.',
  },
  {
    id: 'educational-slide',
    label: 'Educational Slide',
    description: 'Explainer-style slide with icon-first education, scale context, and actions.',
  },
]

const templateLabelMap = Object.fromEntries(
  templateOptions.map((option) => [option.id, option.label]),
) as Record<SocialGraphicsTemplateId, string>

function cloneScene(scene: SocialGraphicsScene): SocialGraphicsScene {
  return JSON.parse(JSON.stringify(scene)) as SocialGraphicsScene
}

function buildScene(
  templateId: SocialGraphicsTemplateId,
  title: string,
  elements: SocialGraphicsElement[],
): SocialGraphicsScene {
  return {
    version: 'social-graphics-v1',
    title,
    templateId,
    width: SOCIAL_GRAPHICS_WIDTH,
    height: SOCIAL_GRAPHICS_HEIGHT,
    elements,
  }
}

function background(fill: string): SocialGraphicsElement {
  return {
    id: 'background',
    name: 'Background',
    kind: 'rect',
    x: 0,
    y: 0,
    width: SOCIAL_GRAPHICS_WIDTH,
    height: SOCIAL_GRAPHICS_HEIGHT,
    visible: true,
    opacity: 1,
    fill,
    cornerRadius: 0,
  }
}

function buildBackgroundImage(): SocialGraphicsElement {
  return {
    id: 'background-image',
    name: 'Background Image',
    kind: 'image',
    x: 0,
    y: 0,
    width: SOCIAL_GRAPHICS_WIDTH,
    height: SOCIAL_GRAPHICS_HEIGHT,
    visible: false,
    opacity: 1,
    src: '/assets/visual-finder/ops-grid-background.svg',
    fit: 'cover',
    cornerRadius: 0,
    assetRole: 'background',
    linkedAssetId: null,
  }
}

function buildLogo(x = 1540, y = 72, width = 240, height = 240): SocialGraphicsElement {
  return {
    id: 'logo',
    name: 'Logo',
    kind: 'image',
    x,
    y,
    width,
    height,
    visible: true,
    opacity: 1,
    src: '/NOAA_logo.png',
    fit: 'contain',
    cornerRadius: 0,
    assetRole: 'logo',
    linkedAssetId: 'noaa-brand-mark',
  }
}

function buildImageSlot({
  id,
  name,
  x,
  y,
  width,
  height,
  src,
  fit = 'contain',
  cornerRadius = 0,
  assetRole,
  linkedAssetId = null,
}: {
  id: string
  name: string
  x: number
  y: number
  width: number
  height: number
  src: string
  fit?: 'cover' | 'contain'
  cornerRadius?: number
  assetRole?: 'background' | 'logo' | 'main-image' | 'secondary-image' | 'icon-slot'
  linkedAssetId?: string | null
}): SocialGraphicsElement {
  return {
    id,
    name,
    kind: 'image',
    x,
    y,
    width,
    height,
    visible: true,
    opacity: 1,
    src,
    fit,
    cornerRadius,
    assetRole,
    linkedAssetId,
  }
}

const briefingSummaryScene = buildScene('briefing-summary', 'Briefing Summary', [
  background('#081a2c'),
  buildBackgroundImage(),
  {
    id: 'aurora-glow',
    name: 'Aurora Glow',
    kind: 'rect',
    x: 1220,
    y: -80,
    width: 820,
    height: 760,
    visible: true,
    opacity: 0.18,
    fill: '#22c7ff',
    cornerRadius: 380,
  },
  {
    id: 'accent-bar',
    name: 'Accent Bar',
    kind: 'rect',
    x: 124,
    y: 108,
    width: 640,
    height: 18,
    visible: true,
    opacity: 1,
    fill: '#5fb7ff',
    cornerRadius: 9,
  },
  {
    id: 'title',
    name: 'Title',
    kind: 'text',
    x: 120,
    y: 178,
    width: 1180,
    height: 220,
    visible: true,
    opacity: 1,
    text: 'Daily Space Weather Briefing',
    fill: '#f4f8ff',
    fontFamily: 'DejaVu Sans',
    fontSize: 88,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.05,
  },
  {
    id: 'subtitle',
    name: 'Subtitle',
    kind: 'text',
    x: 126,
    y: 430,
    width: 1040,
    height: 220,
    visible: true,
    opacity: 1,
    text: 'Active regions continue to support elevated flare potential. Confidence is moderate for minor geomagnetic response in the next 24 to 48 hours.',
    fill: '#dce9f8',
    fontFamily: 'DejaVu Sans',
    fontSize: 40,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.3,
  },
  {
    id: 'footer-line',
    name: 'Footer Line',
    kind: 'line',
    x: 126,
    y: 940,
    width: 1660,
    height: 0,
    visible: true,
    opacity: 1,
    stroke: '#6bb4ff',
    strokeWidth: 8,
  },
  {
    id: 'footer',
    name: 'Footer',
    kind: 'text',
    x: 126,
    y: 962,
    width: 1060,
    height: 64,
    visible: true,
    opacity: 1,
    text: 'SWPC | PartnerBrief Hub | Operational Decision Support',
    fill: '#c3d7ef',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.2,
  },
  buildLogo(),
])

const eventAlertCardScene = buildScene('event-alert-card', 'Event Alert Card', [
  background('#06111f'),
  buildBackgroundImage(),
  {
    id: 'alert-rail',
    name: 'Alert Rail',
    kind: 'rect',
    x: 0,
    y: 0,
    width: 72,
    height: SOCIAL_GRAPHICS_HEIGHT,
    visible: true,
    opacity: 1,
    fill: '#ff7a33',
    cornerRadius: 0,
  },
  {
    id: 'alert-banner',
    name: 'Alert Banner',
    kind: 'rect',
    x: 130,
    y: 110,
    width: 340,
    height: 72,
    visible: true,
    opacity: 1,
    fill: '#ff9a4c',
    cornerRadius: 18,
  },
  {
    id: 'alert-label',
    name: 'Alert Label',
    kind: 'text',
    x: 178,
    y: 126,
    width: 250,
    height: 44,
    visible: true,
    opacity: 1,
    text: 'ALERT',
    fill: '#132033',
    fontFamily: 'DejaVu Sans',
    fontSize: 34,
    fontWeight: 700,
    align: 'center',
    lineHeight: 1,
  },
  {
    id: 'title',
    name: 'Title',
    kind: 'text',
    x: 130,
    y: 240,
    width: 960,
    height: 230,
    visible: true,
    opacity: 1,
    text: 'Geomagnetic Storm Watch In Effect',
    fill: '#f9fbff',
    fontFamily: 'DejaVu Sans',
    fontSize: 96,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.02,
  },
  {
    id: 'subtitle',
    name: 'Subtitle',
    kind: 'text',
    x: 136,
    y: 500,
    width: 890,
    height: 220,
    visible: true,
    opacity: 1,
    text: 'Expected impacts include intermittent HF degradation, increased satellite charging concern, and elevated auroral visibility at lower latitudes.',
    fill: '#dce8f5',
    fontFamily: 'DejaVu Sans',
    fontSize: 40,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.28,
  },
  {
    id: 'image-frame',
    name: 'Image Frame',
    kind: 'rect',
    x: 1168,
    y: 148,
    width: 614,
    height: 774,
    visible: true,
    opacity: 1,
    fill: '#102945',
    cornerRadius: 34,
  },
  {
    id: 'secondary-image',
    name: 'Secondary Image',
    kind: 'image',
    x: 1190,
    y: 170,
    width: 570,
    height: 730,
    visible: true,
    opacity: 1,
    src: '/NOAA_logo.png',
    fit: 'contain',
    cornerRadius: 28,
    assetRole: 'main-image',
    linkedAssetId: 'noaa-brand-mark',
  },
  buildLogo(),
])

const partnerSpotlightScene = buildScene('partner-spotlight', 'Partner Spotlight', [
  background('#071423'),
  buildBackgroundImage(),
  {
    id: 'left-panel',
    name: 'Left Panel',
    kind: 'rect',
    x: 72,
    y: 72,
    width: 960,
    height: 936,
    visible: true,
    opacity: 1,
    fill: '#0b2340',
    cornerRadius: 40,
  },
  {
    id: 'title',
    name: 'Title',
    kind: 'text',
    x: 126,
    y: 154,
    width: 820,
    height: 190,
    visible: true,
    opacity: 1,
    text: 'Partner Spotlight',
    fill: '#f6f9ff',
    fontFamily: 'DejaVu Sans',
    fontSize: 84,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.04,
  },
  {
    id: 'subtitle',
    name: 'Subtitle',
    kind: 'text',
    x: 126,
    y: 352,
    width: 790,
    height: 340,
    visible: true,
    opacity: 1,
    text: 'Highlight how your operations team uses impact-based decision support. Add a short quote, a key action, or a campaign announcement in this space.',
    fill: '#d7e5f4',
    fontFamily: 'DejaVu Sans',
    fontSize: 40,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.32,
  },
  {
    id: 'callout-bar',
    name: 'Callout Bar',
    kind: 'rect',
    x: 126,
    y: 826,
    width: 460,
    height: 18,
    visible: true,
    opacity: 1,
    fill: '#63c7ff',
    cornerRadius: 9,
  },
  {
    id: 'callout',
    name: 'Callout',
    kind: 'text',
    x: 126,
    y: 868,
    width: 820,
    height: 100,
    visible: true,
    opacity: 1,
    text: 'Partner-ready announcement or highlight block',
    fill: '#f6fbff',
    fontFamily: 'DejaVu Sans',
    fontSize: 34,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.18,
  },
  {
    id: 'image-frame',
    name: 'Image Frame',
    kind: 'rect',
    x: 1084,
    y: 120,
    width: 718,
    height: 840,
    visible: true,
    opacity: 1,
    fill: '#12345a',
    cornerRadius: 42,
  },
  {
    id: 'secondary-image',
    name: 'Secondary Image',
    kind: 'image',
    x: 1108,
    y: 144,
    width: 670,
    height: 792,
    visible: true,
    opacity: 1,
    src: '/NOAA_logo.png',
    fit: 'contain',
    cornerRadius: 36,
    assetRole: 'main-image',
    linkedAssetId: 'noaa-brand-mark',
  },
  buildLogo(),
])

const informedDesignEventScene = buildScene('informed-design-event', 'Informed Design Event', [
  background('#e9ecef'),
  buildBackgroundImage(),
  {
    id: 'outer-shell',
    name: 'Outer Shell',
    kind: 'rect',
    x: 84,
    y: 64,
    width: 1752,
    height: 952,
    visible: true,
    opacity: 1,
    fill: '#f7f8fa',
    cornerRadius: 0,
  },
  {
    id: 'header-band',
    name: 'Header Band',
    kind: 'rect',
    x: 84,
    y: 64,
    width: 1752,
    height: 20,
    visible: true,
    opacity: 1,
    fill: '#11a7de',
    cornerRadius: 0,
  },
  {
    id: 'left-rail',
    name: 'Left Rail',
    kind: 'rect',
    x: 84,
    y: 84,
    width: 268,
    height: 932,
    visible: true,
    opacity: 1,
    fill: '#355c9c',
    cornerRadius: 0,
  },
  {
    id: 'content-shell',
    name: 'Content Shell',
    kind: 'rect',
    x: 178,
    y: 126,
    width: 1508,
    height: 746,
    visible: true,
    opacity: 1,
    fill: '#1f1f22',
    cornerRadius: 0,
  },
  {
    id: 'title',
    name: 'Title',
    kind: 'text',
    x: 240,
    y: 158,
    width: 820,
    height: 108,
    visible: true,
    opacity: 1,
    text: 'Hazardous Space Weather Travel',
    fill: '#ffffff',
    fontFamily: 'DejaVu Sans',
    fontSize: 66,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.02,
  },
  {
    id: 'headline-deck',
    name: 'Headline Deck',
    kind: 'text',
    x: 244,
    y: 238,
    width: 720,
    height: 84,
    visible: true,
    opacity: 1,
    text: 'Strong geomagnetic conditions may create degraded communications and navigation concerns through tonight.',
    fill: '#f2f4f7',
    fontFamily: 'DejaVu Sans',
    fontSize: 30,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.16,
  },
  {
    id: 'timing-badge',
    name: 'Timing Badge',
    kind: 'rect',
    x: 1088,
    y: 152,
    width: 484,
    height: 74,
    visible: true,
    opacity: 1,
    fill: '#ffffff',
    cornerRadius: 0,
  },
  {
    id: 'timing-text',
    name: 'Timing Text',
    kind: 'text',
    x: 1140,
    y: 170,
    width: 386,
    height: 42,
    visible: true,
    opacity: 1,
    text: 'Through Early Wednesday UTC',
    fill: '#2d2f36',
    fontFamily: 'DejaVu Sans',
    fontSize: 34,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1,
  },
  {
    id: 'timing-accent',
    name: 'Timing Accent',
    kind: 'line',
    x: 1088,
    y: 226,
    width: 484,
    height: 0,
    visible: true,
    opacity: 1,
    stroke: '#f79f3b',
    strokeWidth: 10,
  },
  {
    id: 'photo-frame',
    name: 'Photo Frame',
    kind: 'rect',
    x: 242,
    y: 324,
    width: 748,
    height: 372,
    visible: true,
    opacity: 1,
    fill: '#203746',
    cornerRadius: 0,
  },
  buildImageSlot({
    id: 'main-image',
    name: 'Main Image',
    x: 242,
    y: 324,
    width: 748,
    height: 372,
    src: '/assets/visual-finder/aurora-ribbon-visual.svg',
    fit: 'cover',
    cornerRadius: 0,
    assetRole: 'main-image',
    linkedAssetId: 'aurora-ribbon-visual',
  }),
  {
    id: 'severity-panel',
    name: 'Severity Panel',
    kind: 'rect',
    x: 242,
    y: 700,
    width: 334,
    height: 132,
    visible: true,
    opacity: 1,
    fill: '#252629',
    cornerRadius: 0,
  },
  {
    id: 'severity-title',
    name: 'Severity Title',
    kind: 'text',
    x: 266,
    y: 726,
    width: 214,
    height: 32,
    visible: true,
    opacity: 1,
    text: 'Weather Risk',
    fill: '#ffffff',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'risk-scale-red',
    name: 'Risk Scale Red',
    kind: 'rect',
    x: 266,
    y: 770,
    width: 176,
    height: 26,
    visible: true,
    opacity: 1,
    fill: '#f44336',
    cornerRadius: 2,
  },
  {
    id: 'risk-scale-orange',
    name: 'Risk Scale Orange',
    kind: 'rect',
    x: 266,
    y: 800,
    width: 120,
    height: 26,
    visible: true,
    opacity: 1,
    fill: '#ff9f2f',
    cornerRadius: 2,
  },
  {
    id: 'risk-scale-yellow',
    name: 'Risk Scale Yellow',
    kind: 'rect',
    x: 266,
    y: 830,
    width: 88,
    height: 26,
    visible: true,
    opacity: 1,
    fill: '#e8df67',
    cornerRadius: 2,
  },
  {
    id: 'risk-label',
    name: 'Risk Label',
    kind: 'text',
    x: 466,
    y: 786,
    width: 90,
    height: 52,
    visible: true,
    opacity: 1,
    text: 'High',
    fill: '#ffffff',
    fontFamily: 'DejaVu Sans',
    fontSize: 32,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1,
  },
  {
    id: 'summary-head',
    name: 'Summary Head',
    kind: 'text',
    x: 1088,
    y: 272,
    width: 482,
    height: 88,
    visible: true,
    opacity: 1,
    text: 'Expected impacts will create hazardous operating conditions for HF communications, aviation routing, and GNSS-dependent planning.',
    fill: '#f79f3b',
    fontFamily: 'DejaVu Sans',
    fontSize: 32,
    fontWeight: 700,
    align: 'center',
    lineHeight: 1.2,
  },
  {
    id: 'impact-card',
    name: 'Impact Card',
    kind: 'rect',
    x: 1088,
    y: 374,
    width: 484,
    height: 220,
    visible: true,
    opacity: 1,
    fill: '#ffffff',
    cornerRadius: 0,
  },
  buildImageSlot({
    id: 'hazard-icon',
    name: 'Hazard Icon',
    x: 1098,
    y: 392,
    width: 108,
    height: 108,
    src: '/assets/visual-finder/hazard-explainer-icon.svg',
    fit: 'contain',
    cornerRadius: 18,
    assetRole: 'icon-slot',
    linkedAssetId: 'hazard-explainer-icon',
  }),
  {
    id: 'impact-copy',
    name: 'Impact Copy',
    kind: 'text',
    x: 1238,
    y: 392,
    width: 318,
    height: 170,
    visible: true,
    opacity: 1,
    text: 'HF users may experience intermittent degradation.\nNavigation confidence may narrow during peak activity windows.',
    fill: '#23262c',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.26,
  },
  {
    id: 'impact-divider',
    name: 'Impact Divider',
    kind: 'line',
    x: 1088,
    y: 596,
    width: 484,
    height: 0,
    visible: true,
    opacity: 1,
    stroke: '#f79f3b',
    strokeWidth: 3,
  },
  {
    id: 'actions-head',
    name: 'Actions Head',
    kind: 'text',
    x: 1088,
    y: 630,
    width: 250,
    height: 38,
    visible: true,
    opacity: 1,
    text: 'Actions to take...',
    fill: '#f79f3b',
    fontFamily: 'DejaVu Sans',
    fontSize: 34,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'actions-copy',
    name: 'Actions Copy',
    kind: 'text',
    x: 1088,
    y: 688,
    width: 486,
    height: 132,
    visible: true,
    opacity: 1,
    text: 'Delay non-critical communications windows.\nMessage timing confidence and affected sectors.\nUse simple, action-oriented wording for partners and the public.',
    fill: '#23262c',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.28,
  },
  {
    id: 'bottom-band',
    name: 'Bottom Band',
    kind: 'rect',
    x: 178,
    y: 872,
    width: 1508,
    height: 144,
    visible: true,
    opacity: 1,
    fill: '#242426',
    cornerRadius: 0,
  },
  {
    id: 'resource-copy',
    name: 'Resource Copy',
    kind: 'text',
    x: 540,
    y: 924,
    width: 680,
    height: 56,
    visible: true,
    opacity: 1,
    text: 'weather.gov/SWPC | Operational Decision Support | Updated 18Z',
    fill: '#f3f6fb',
    fontFamily: 'DejaVu Sans',
    fontSize: 26,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.2,
  },
  buildLogo(216, 896, 112, 112),
])

const partnerImpactBriefScene = buildScene('partner-impact-brief', 'Partner Impact Brief', [
  background('#071320'),
  buildBackgroundImage(),
  {
    id: 'briefing-shell',
    name: 'Briefing Shell',
    kind: 'rect',
    x: 64,
    y: 60,
    width: 1792,
    height: 960,
    visible: true,
    opacity: 1,
    fill: '#0c223b',
    cornerRadius: 34,
  },
  {
    id: 'impact-column',
    name: 'Impact Column',
    kind: 'rect',
    x: 1210,
    y: 138,
    width: 520,
    height: 740,
    visible: true,
    opacity: 1,
    fill: '#102f4f',
    cornerRadius: 28,
  },
  {
    id: 'title',
    name: 'Title',
    kind: 'text',
    x: 136,
    y: 150,
    width: 920,
    height: 168,
    visible: true,
    opacity: 1,
    text: 'Partner Impact Brief',
    fill: '#f6faff',
    fontFamily: 'DejaVu Sans',
    fontSize: 82,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.05,
  },
  {
    id: 'subtitle',
    name: 'Subtitle',
    kind: 'text',
    x: 140,
    y: 356,
    width: 900,
    height: 376,
    visible: true,
    opacity: 1,
    text: 'Elevated geomagnetic conditions remain possible through the next operational period. Expected partner impacts include intermittent HF degradation, mild satellite charging concern, and increased auroral visibility at higher latitudes.',
    fill: '#d8e6f5',
    fontFamily: 'DejaVu Sans',
    fontSize: 38,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.34,
  },
  {
    id: 'callout-title',
    name: 'Callout Title',
    kind: 'text',
    x: 1260,
    y: 186,
    width: 410,
    height: 90,
    visible: true,
    opacity: 1,
    text: 'Partner Actions',
    fill: '#f6fbff',
    fontFamily: 'DejaVu Sans',
    fontSize: 42,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'callout-body',
    name: 'Callout Body',
    kind: 'text',
    x: 1260,
    y: 292,
    width: 410,
    height: 440,
    visible: true,
    opacity: 1,
    text: 'Review contingency communications.\nCoordinate with affected operations teams.\nHighlight timing confidence and expected recovery windows.',
    fill: '#d9e7f5',
    fontFamily: 'DejaVu Sans',
    fontSize: 32,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.45,
  },
  {
    id: 'footer-line',
    name: 'Footer Line',
    kind: 'line',
    x: 136,
    y: 900,
    width: 1592,
    height: 0,
    visible: true,
    opacity: 1,
    stroke: '#6eb8ff',
    strokeWidth: 7,
  },
  {
    id: 'footer',
    name: 'Footer',
    kind: 'text',
    x: 140,
    y: 922,
    width: 1120,
    height: 56,
    visible: true,
    opacity: 1,
    text: 'NOAA Space Weather Prediction Center | IDSS partner briefing slide',
    fill: '#c3d7ef',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.2,
  },
  buildLogo(1580, 96, 184, 184),
])

const operationalSnapshotScene = buildScene('operational-snapshot', 'Operational Snapshot', [
  background('#08121e'),
  buildBackgroundImage(),
  {
    id: 'header-band',
    name: 'Header Band',
    kind: 'rect',
    x: 0,
    y: 0,
    width: SOCIAL_GRAPHICS_WIDTH,
    height: 212,
    visible: true,
    opacity: 1,
    fill: '#0f2a47',
    cornerRadius: 0,
  },
  {
    id: 'title',
    name: 'Title',
    kind: 'text',
    x: 128,
    y: 72,
    width: 980,
    height: 96,
    visible: true,
    opacity: 1,
    text: 'Operational Snapshot',
    fill: '#f7fbff',
    fontFamily: 'DejaVu Sans',
    fontSize: 78,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.04,
  },
  {
    id: 'summary-card',
    name: 'Summary Card',
    kind: 'rect',
    x: 112,
    y: 274,
    width: 760,
    height: 640,
    visible: true,
    opacity: 1,
    fill: '#0b223b',
    cornerRadius: 28,
  },
  {
    id: 'summary-text',
    name: 'Summary Text',
    kind: 'text',
    x: 152,
    y: 324,
    width: 676,
    height: 526,
    visible: true,
    opacity: 1,
    text: 'Conditions:\nMinor geomagnetic response remains possible.\n\nImpacts:\nHF users may see intermittent degradation.\nGNSS effects remain limited but possible near higher latitudes.\n\nConfidence:\nModerate through the next 24 hours.',
    fill: '#deebf9',
    fontFamily: 'DejaVu Sans',
    fontSize: 34,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.4,
  },
  {
    id: 'image-frame',
    name: 'Image Frame',
    kind: 'rect',
    x: 938,
    y: 274,
    width: 848,
    height: 640,
    visible: true,
    opacity: 1,
    fill: '#102d4b',
    cornerRadius: 28,
  },
  {
    id: 'secondary-image',
    name: 'Secondary Image',
    kind: 'image',
    x: 984,
    y: 322,
    width: 754,
    height: 544,
    visible: true,
    opacity: 1,
    src: '/NOAA_logo.png',
    fit: 'contain',
    cornerRadius: 20,
    assetRole: 'main-image',
    linkedAssetId: 'noaa-brand-mark',
  },
  buildLogo(1604, 32, 164, 164),
])

const decisionSupportFocusScene = buildScene('decision-support-focus', 'Decision Support Focus', [
  background('#06101a'),
  buildBackgroundImage(),
  {
    id: 'top-accent',
    name: 'Top Accent',
    kind: 'rect',
    x: 108,
    y: 96,
    width: 540,
    height: 18,
    visible: true,
    opacity: 1,
    fill: '#62c4ff',
    cornerRadius: 9,
  },
  {
    id: 'title',
    name: 'Title',
    kind: 'text',
    x: 108,
    y: 154,
    width: 980,
    height: 174,
    visible: true,
    opacity: 1,
    text: 'Decision Support Focus',
    fill: '#f7fbff',
    fontFamily: 'DejaVu Sans',
    fontSize: 88,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.02,
  },
  {
    id: 'subtitle',
    name: 'Subtitle',
    kind: 'text',
    x: 112,
    y: 360,
    width: 930,
    height: 330,
    visible: true,
    opacity: 1,
    text: 'Use this slide to frame the operational decision, the expected impact window, and the recommended communication posture for partners and leadership.',
    fill: '#dce9f8',
    fontFamily: 'DejaVu Sans',
    fontSize: 40,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.34,
  },
  {
    id: 'decision-card',
    name: 'Decision Card',
    kind: 'rect',
    x: 1156,
    y: 170,
    width: 620,
    height: 712,
    visible: true,
    opacity: 1,
    fill: '#0d2743',
    cornerRadius: 30,
  },
  {
    id: 'decision-header',
    name: 'Decision Header',
    kind: 'text',
    x: 1212,
    y: 232,
    width: 500,
    height: 68,
    visible: true,
    opacity: 1,
    text: 'Operational Focus',
    fill: '#f8fbff',
    fontFamily: 'DejaVu Sans',
    fontSize: 40,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'decision-body',
    name: 'Decision Body',
    kind: 'text',
    x: 1212,
    y: 330,
    width: 500,
    height: 450,
    visible: true,
    opacity: 1,
    text: 'Decision:\nElevate partner awareness messaging.\n\nWindow:\n00Z to 18Z tomorrow.\n\nWhy it matters:\nMinor communication disruptions remain possible during key planning periods.',
    fill: '#dbe8f6',
    fontFamily: 'DejaVu Sans',
    fontSize: 32,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.42,
  },
  buildLogo(1556, 898, 172, 172),
])

const educationalSlideScene = buildScene('educational-slide', 'Educational Slide', [
  background('#eceef1'),
  buildBackgroundImage(),
  {
    id: 'outer-shell',
    name: 'Outer Shell',
    kind: 'rect',
    x: 84,
    y: 64,
    width: 1752,
    height: 952,
    visible: true,
    opacity: 1,
    fill: '#f8f8fa',
    cornerRadius: 0,
  },
  {
    id: 'top-stripe',
    name: 'Top Stripe',
    kind: 'rect',
    x: 84,
    y: 64,
    width: 1752,
    height: 18,
    visible: true,
    opacity: 1,
    fill: '#11a7de',
    cornerRadius: 0,
  },
  {
    id: 'left-rail',
    name: 'Left Rail',
    kind: 'rect',
    x: 84,
    y: 84,
    width: 208,
    height: 932,
    visible: true,
    opacity: 1,
    fill: '#355c9c',
    cornerRadius: 0,
  },
  {
    id: 'feature-block',
    name: 'Feature Block',
    kind: 'rect',
    x: 206,
    y: 128,
    width: 744,
    height: 820,
    visible: true,
    opacity: 1,
    fill: '#d53f3f',
    cornerRadius: 0,
  },
  {
    id: 'top-label',
    name: 'Top Label',
    kind: 'text',
    x: 270,
    y: 170,
    width: 620,
    height: 36,
    visible: true,
    opacity: 1,
    text: 'SWPC Educational Explainer',
    fill: '#fff9fb',
    fontFamily: 'DejaVu Sans',
    fontSize: 32,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1,
  },
  buildImageSlot({
    id: 'education-icon',
    name: 'Education Icon',
    x: 390,
    y: 274,
    width: 374,
    height: 374,
    src: '/assets/visual-finder/hazard-explainer-icon.svg',
    fit: 'contain',
    cornerRadius: 32,
    assetRole: 'icon-slot',
    linkedAssetId: 'hazard-explainer-icon',
  }),
  {
    id: 'education-title',
    name: 'Education Title',
    kind: 'text',
    x: 270,
    y: 706,
    width: 560,
    height: 108,
    visible: true,
    opacity: 1,
    text: 'What does a High Space Weather Risk mean?',
    fill: '#ffffff',
    fontFamily: 'DejaVu Sans',
    fontSize: 58,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.08,
  },
  {
    id: 'right-panel',
    name: 'Right Panel',
    kind: 'rect',
    x: 950,
    y: 128,
    width: 736,
    height: 820,
    visible: true,
    opacity: 1,
    fill: '#ffffff',
    cornerRadius: 0,
  },
  {
    id: 'severity-caption',
    name: 'Severity Caption',
    kind: 'text',
    x: 1326,
    y: 168,
    width: 280,
    height: 92,
    visible: true,
    opacity: 1,
    text: 'High Impact Risk is the\n3rd of 4 levels',
    fill: '#d53f3f',
    fontFamily: 'DejaVu Sans',
    fontSize: 34,
    fontWeight: 700,
    align: 'center',
    lineHeight: 1.18,
  },
  {
    id: 'severity-scale-1',
    name: 'Severity Scale 1',
    kind: 'rect',
    x: 1010,
    y: 168,
    width: 198,
    height: 28,
    visible: true,
    opacity: 1,
    fill: '#7f3fb8',
    cornerRadius: 2,
  },
  {
    id: 'severity-scale-2',
    name: 'Severity Scale 2',
    kind: 'rect',
    x: 1010,
    y: 212,
    width: 298,
    height: 36,
    visible: true,
    opacity: 1,
    fill: '#ea3939',
    cornerRadius: 2,
  },
  {
    id: 'severity-scale-3',
    name: 'Severity Scale 3',
    kind: 'rect',
    x: 1010,
    y: 266,
    width: 176,
    height: 28,
    visible: true,
    opacity: 1,
    fill: '#f5a338',
    cornerRadius: 2,
  },
  {
    id: 'severity-scale-4',
    name: 'Severity Scale 4',
    kind: 'rect',
    x: 1010,
    y: 310,
    width: 128,
    height: 28,
    visible: true,
    opacity: 1,
    fill: '#c9cb61',
    cornerRadius: 2,
  },
  {
    id: 'severity-line',
    name: 'Severity Line',
    kind: 'line',
    x: 1010,
    y: 372,
    width: 596,
    height: 0,
    visible: true,
    opacity: 1,
    stroke: '#e3a35f',
    strokeWidth: 3,
  },
  {
    id: 'meaning-title',
    name: 'Meaning Title',
    kind: 'text',
    x: 1036,
    y: 410,
    width: 232,
    height: 40,
    visible: true,
    opacity: 1,
    text: 'What it means:',
    fill: '#555962',
    fontFamily: 'DejaVu Sans',
    fontSize: 32,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'meaning-copy',
    name: 'Meaning Copy',
    kind: 'text',
    x: 1038,
    y: 466,
    width: 262,
    height: 302,
    visible: true,
    opacity: 1,
    text: 'High risk of operational impacts for some users.\n\nCommunications, routing, or timing confidence may be reduced.\n\nConditions may persist long enough to affect planning windows.',
    fill: '#4b4f58',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.34,
  },
  {
    id: 'actions-title',
    name: 'Actions Title',
    kind: 'text',
    x: 1380,
    y: 410,
    width: 230,
    height: 40,
    visible: true,
    opacity: 1,
    text: 'Actions to take:',
    fill: '#555962',
    fontFamily: 'DejaVu Sans',
    fontSize: 32,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.1,
  },
  {
    id: 'actions-copy',
    name: 'Actions Copy',
    kind: 'text',
    x: 1382,
    y: 466,
    width: 244,
    height: 302,
    visible: true,
    opacity: 1,
    text: 'Review the latest forecast.\n\nUse simple, direct messaging.\n\nHighlight what could happen, who may be affected, and what action is useful now.',
    fill: '#4b4f58',
    fontFamily: 'DejaVu Sans',
    fontSize: 28,
    fontWeight: 400,
    align: 'left',
    lineHeight: 1.34,
  },
  {
    id: 'resource-card',
    name: 'Resource Card',
    kind: 'rect',
    x: 486,
    y: 906,
    width: 260,
    height: 78,
    visible: true,
    opacity: 1,
    fill: '#355c9c',
    cornerRadius: 12,
  },
  {
    id: 'resource-copy',
    name: 'Resource Copy',
    kind: 'text',
    x: 786,
    y: 920,
    width: 676,
    height: 56,
    visible: true,
    opacity: 1,
    text: 'Resource: Informed design guidance | clear scale + hazard meaning + actions',
    fill: '#2c2f37',
    fontFamily: 'DejaVu Sans',
    fontSize: 26,
    fontWeight: 700,
    align: 'left',
    lineHeight: 1.2,
  },
  buildLogo(1492, 848, 120, 120),
])

const scenes: Record<SocialGraphicsTemplateId, SocialGraphicsScene> = {
  'briefing-summary': briefingSummaryScene,
  'event-alert-card': eventAlertCardScene,
  'informed-design-event': informedDesignEventScene,
  'partner-spotlight': partnerSpotlightScene,
  'partner-impact-brief': partnerImpactBriefScene,
  'operational-snapshot': operationalSnapshotScene,
  'decision-support-focus': decisionSupportFocusScene,
  'educational-slide': educationalSlideScene,
}

export function createSceneFromTemplate(templateId: SocialGraphicsTemplateId): SocialGraphicsScene {
  return cloneScene(scenes[templateId])
}

export function getGraphicsTemplateOptions(mode: GraphicsWorkspaceMode): SocialGraphicsTemplateOption[] {
  return templateOptions.filter((option) => templateModeMap[option.id] === mode)
}

export function getDefaultTemplateId(mode: GraphicsWorkspaceMode): SocialGraphicsTemplateId {
  const match = templateOptions.find((option) => templateModeMap[option.id] === mode)
  return match?.id ?? 'briefing-summary'
}

export function templateBelongsToMode(
  templateId: SocialGraphicsTemplateId,
  mode: GraphicsWorkspaceMode,
): boolean {
  return templateModeMap[templateId] === mode
}

export function graphicsTemplateLabel(templateId: SocialGraphicsTemplateId): string {
  return templateLabelMap[templateId]
}
