<script setup lang="ts">
import { computed, ref } from 'vue'

const steps = [
  { id: 'synopsis', number: '1', label: 'Synopsis', title: 'Establish the shared situation', goal: 'Create the common operational narrative that the other briefing products will inherit.', actions: ['Confirm the runtime clock and the source products represented in the workspace.', 'Summarize what is happening, expected timing, confidence, and the main operational impacts.', 'Save the synopsis before building audience-specific products so every version starts from the same assessment.'], ready: 'The situation, timing, confidence, and source basis are current and understandable without opening a forecast console.' },
  { id: 'core', number: '2', label: 'Core Brief', title: 'Build the standard distribution brief', goal: 'Turn the reviewed synopsis into the routine partner communication without changing its scientific meaning.', actions: ['Choose the intended distribution and confirm the issue and valid times.', 'Review subject, summary, impacts, actions, and uncertainty for plain-language consistency.', 'Preview the complete brief and resolve missing or stale content before export or distribution.'], ready: 'The core brief accurately represents the saved synopsis and is appropriate for its declared audience and time window.' },
  { id: 'tailored', number: '3', label: 'Tailored Brief', title: 'Adapt the message for one partner', goal: 'Emphasize the exposure and actions relevant to a specific partner while preserving the common forecast.', actions: ['Select the partner and review its sector, mission, and delivery context.', 'Edit impacts and recommended actions for that partner; retain shared timing and confidence.', 'Check that tailored language does not introduce an unsupported hazard, certainty, or local impact claim.'], ready: 'The recipient can identify what matters to them, when it matters, and what action the forecast supports.' },
  { id: 'media', number: '4', label: 'Media', title: 'Prepare a visual communication product', goal: 'Create a concise graphic from the reviewed briefing content for the selected public or partner channel.', actions: ['Choose the format and confirm its displayed time, scale, and attribution.', 'Keep the headline, impacts, and action language short enough to read at the intended size.', 'Inspect the final graphic for clipping, contrast, source labels, and consistency with the saved synopsis.'], ready: 'The exported visual is legible, time stamped, attributed, and scientifically consistent with the reviewed briefing.' },
]
const activeId = ref('synopsis')
const active = computed(() => steps.find(step => step.id === activeId.value) ?? steps[0]!)
const checks = ['Runtime mode and UTC clock match the intended session.', 'The source forecast or issued product is current for the briefing.', 'Hazard timing, confidence, and uncertainty are preserved across versions.', 'Missing information remains visible and is not converted into a reassuring statement.', 'Partner language describes plausible effects without asserting an observed local impact.', 'The preview has no clipped text, placeholder content, or unintended recipients.', 'Replay and exercise products remain clearly separated from operational distribution.']
</script>

<template>
  <div class="guide">
    <header class="hero"><div class="eyebrow">Operational quick path</div><h2>Build one assessment into clear briefings</h2><p>Start with the shared synopsis, then adapt its reviewed content for routine distribution, a specific partner, or a visual channel.</p><div class="facts"><span>One shared assessment</span><span>Audience-specific language</span><span>Preview before release</span></div></header>
    <nav class="tabs" aria-label="Briefing workflow"><button v-for="step in steps" :key="step.id" type="button" :class="{ active: activeId === step.id }" :aria-pressed="activeId === step.id" @click="activeId = step.id"><span>{{ step.number }}</span>{{ step.label }}</button></nav>
    <section class="step"><div class="heading"><span>Workspace {{ active.number }} of 4</span><h3>{{ active.title }}</h3><p>{{ active.goal }}</p></div><ol><li v-for="action in active.actions" :key="action">{{ action }}</li></ol><div class="ready"><span>Continue when</span>{{ active.ready }}</div></section>
    <section class="reference">
      <details><summary><span>Know what this application owns</span><small>Communication built from reviewed forecasts</small></summary><div class="grid"><div><h4>Forecast applications</h4><p>Own the scientific guidance, forecaster edits, and source decision records.</p></div><div><h4>Briefing &amp; Synopsis</h4><p>Owns audience, wording, layout, and communication products built from those reviewed records.</p></div><div><h4>Product Launcher</h4><p>Owns formal product review and lifecycle actions for products sent through that workflow.</p></div><div><h4>Replay sessions</h4><p>Support training and retrospective review; their outputs remain identified by the replay clock.</p></div></div></details>
      <details><summary><span>Before distributing</span><small>Seven communication checks</small></summary><ul><li v-for="check in checks" :key="check">{{ check }}</li></ul></details>
    </section>
  </div>
</template>

<style scoped>
.guide{display:grid;gap:18px;color:var(--app-text)}.hero{padding:20px 24px;border:1px solid rgba(95,199,255,.3);border-radius:16px;background:radial-gradient(circle at top right,rgba(95,199,255,.16),transparent 48%),rgba(9,26,43,.72)}.eyebrow,.heading>span,.ready span{color:#84d4eb;font-size:11px;letter-spacing:.1em;text-transform:uppercase}.hero h2{margin:5px 0 7px;font-size:clamp(22px,2vw,30px);font-weight:500}.hero p,.heading p{margin:0;color:#c8d8e8;line-height:1.5}.facts{display:flex;flex-wrap:wrap;gap:7px;margin-top:14px}.facts span{padding:6px 10px;border:1px solid rgba(151,205,231,.25);border-radius:999px;background:rgba(151,205,231,.08);font-size:11px}.tabs{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.tabs button{display:grid;justify-items:start;gap:3px;min-height:54px;padding:8px 10px;border:1px solid rgba(151,205,231,.28);border-radius:9px;background:#122b40;color:#c8d8e8;cursor:pointer;font:500 12px inherit}.tabs button span{color:#84d4eb;font:500 11px Consolas,monospace}.tabs button.active{border-color:#77d9f4;background:#36aeda;color:#07131f}.tabs button.active span{color:#07131f}.step{display:grid;grid-template-columns:minmax(240px,.75fr) minmax(400px,1fr);gap:18px 30px;padding:22px;border:1px solid var(--app-border-soft);border-radius:14px;background:rgba(13,32,51,.68)}.heading h3{margin:5px 0 7px;font-size:20px;font-weight:500}.step ol{display:grid;gap:8px;margin:0;padding-left:24px;color:#dbe8f1;font-size:13px;line-height:1.5}.ready{grid-column:1/-1;padding:11px 13px;border-left:3px solid #75d6ef;background:#102e43;color:#e6f3f9;font-size:12px}.ready span{margin-right:9px}.reference{display:grid;gap:8px}.reference details{border:1px solid rgba(151,205,231,.2);border-radius:10px;background:#0a1d2f}.reference summary{display:grid;grid-template-columns:minmax(210px,.3fr) 1fr;gap:18px;padding:13px 15px;cursor:pointer}.reference summary span{font-size:14px}.reference summary small{color:#b6c8d8;font-size:12px}.reference details[open] summary{border-bottom:1px solid rgba(151,205,231,.18)}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;padding:14px}.grid div{padding:12px 14px;border-radius:9px;background:#10283b}.grid h4{margin:0 0 5px;font-size:13px;font-weight:500}.grid p{margin:0;color:#c8d8e8;font-size:12px;line-height:1.45}.reference ul{columns:2;margin:0;padding:14px 28px 16px 38px;color:#d4e2ee;font-size:12px;line-height:1.5}.reference li{break-inside:avoid;margin-bottom:6px}@media(max-width:800px){.tabs{grid-template-columns:repeat(2,1fr)}.step,.grid{grid-template-columns:1fr}.ready{grid-column:auto}}@media(max-width:520px){.tabs{grid-template-columns:1fr}.reference summary{grid-template-columns:1fr;gap:4px}.reference ul{columns:1}}
</style>
